apiVersion: apps/v1
kind: Deployment
metadata:
  name: bc-explorer
  namespace: baas-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bc-explorer
  template:
    metadata:
      labels:
        app: bc-explorer
    spec:
      serviceAccountName: bc-explorer
      containers:
      - name: viewer
        image: hyperledgerk8s/bc-explorer:v0.1.0
        command:
        - viewer
        args:
        - -v=5
        - -dsn=postgres://username:password@postgresql.172.22.96.209.nip.io/bc-explorer?sslmode=disable
        ports:
        - containerPort: 9998
      - name: listener
        image:  hyperledgerk8s/bc-explorer:v0.1.0
        command:
        - listener
        args:
        - -v=4
        - -dsn=postgres://username:password@postgresql.172.22.96.209.nip.io/bc-explorer?sslmode=disable
        ports:
        - containerPort: 9999
      - name: observer
        image: hyperledgerk8s/bc-explorer:v0.1.0
        command:
          - observer
        args:
          - -v=5
          - -host=http://127.0.0.1:9999
